import React, { useRef } from "react";

import { Slider } from '../components/Slider'

export default function RootLayout() {

  return (
      <Slider>
        <div>
            event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)
        </div>
        <div>
        event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)event - compiled client and server successfully in 78 ms (170 modules)
            wait  - compiling...
            event - compiled client and server successfully in 103 ms (167 modules)
            wait  - compiling...
            event - compiled client and server successfully in 70 ms (167 modules)
        </div>
        <div>hi</div>
      </Slider>
  );
}